### ISSUE TITLE
BUG: HEAT template generator produces wrong network references in subnets

### ISSUE THREAD

**Issue by mpeuster** [sonata-nfv/son-sp-infrabstract#80]
Hi,

I am currently working towards the SONATA SP to emulator integration and I am not sure if I found a bug in the IA or if this is the correct way to create heat templates.

The possible problem is shown in the code snippets below which show parts of the heat template that is generated by the IA and sent to the VIM.

```yaml
emulator-socat-vnf.output.net.9df6a98f-9e11-4cb7-b3c2-InAdUnitTest-01:
    type: "OS::Neutron::Net"
    properties:
      name: "emulator-socat-vnf.output.net.9df6a98f-9e11-4cb7-b3c2-InAdUnitTest-01"
```

```yaml
emulator-socat-vnf.output.subnet.9df6a98f-9e11-4cb7-b3c2-InAdUnitTest-01:
    type: "OS::Neutron::Subnet"
    properties:
      name: "emulator-socat-vnf.output.subnet.9df6a98f-9e11-4cb7-b3c2-InAdUnitTest-01"
      cidr: "172.0.0.64/27"
      dns_nameservers:
      - "8.8.8.8"
      network:
        get_resource: "emulator-socat-vnf.output:net:9df6a98f-9e11-4cb7-b3c2-InAdUnitTest-01"
```

The first snipped defines a `OS::Neutron::Net` with the name `emulator-socat-vnf.output.net.9df6a98f-9e11-4cb7-b3c2-InAdUnitTest-01`. This looks OK.

The second snipped defines a `OS::Neutron::Subnet` and tries to reference the network `get_resource: "emulator-socat-vnf.output:net:9df6a98f-9e11-4cb7-b3c2-InAdUnitTest-01"` and this does not match to the name of the previously defined network!

Problem is the `.net.` vs. `:net:` in the name/reference.

Is this really the correct behavior?
